name: Update Random Quote

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # install both jq and the CA certificates bundle
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq ca-certificates

      - name: Fetch quote from Quotable
        id: get_quote
        run: |
          DATA=$(curl -s https://api.quotable.io/random)
          CONTENT=$(echo "$DATA" | jq -r '.content')
          AUTHOR=$(echo "$DATA" | jq -r '.author')
          echo "QUOTE=“$CONTENT” — $AUTHOR" >> $GITHUB_ENV

      - name: Inject quote into README
        run: |
          sed -i "s@> “Loading quote…” — \*Author\*@> $QUOTE@" README.md

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet || git commit -m "chore: update random quote"
          git push

